package skillbill.workflow.taskruntime

import skillbill.workflow.taskruntime.model.FeatureTaskRuntimeWireArtifactKind as ModelFeatureTaskRuntimeWireArtifactKind

typealias FeatureTaskRuntimeWireArtifactKind = ModelFeatureTaskRuntimeWireArtifactKind
