package skillbill.workflow.taskruntime

enum class FeatureTaskRuntimeWireArtifactKind {
  QUARANTINE_RECORD,
  PLANNING_PROJECTION,
  IMPLEMENTATION_ATTEMPT,
  BUILD_RECEIPT,
  HANDOFF_DECLARATION,
  HANDOFF_PERSISTENCE_RECORD,
  HANDOFF_MEASUREMENT,
  HANDOFF_SHARED_EVIDENCE_PROJECTION,
  HANDOFF_ENVELOPE,
  GOAL_PROGRESS_EVENT,
  GOAL_OBSERVABILITY_EVENT,
  GOAL_PLANNING_PREPARATION_ENVELOPE,
}
