package skillbill.engine.featuretask.model.review
import skillbill.workflow.taskruntime.model.handoff.task.FeatureTaskRuntimeSharedEvidenceMeasurement
import skillbill.workflow.taskruntime.model.phase.FeatureTaskRuntimeSharedReviewEvidenceReference

data class FeatureTaskRuntimeSharedReviewEvidenceResolved(
  val reference: FeatureTaskRuntimeSharedReviewEvidenceReference,
  val measurement: FeatureTaskRuntimeSharedEvidenceMeasurement,
)
