package skillbill.infrastructure.skills.nativeagent

import skillbill.infrastructure.skills.nativeagent.platformpack.InstallNativeAgentPlatformPackLoader
import skillbill.infrastructure.skills.nativeagent.platformpack.NativeAgentPlatformPackLoader

internal object FileSystemNativeAgentPlatformPackLoader :
  NativeAgentPlatformPackLoader by InstallNativeAgentPlatformPackLoader
