package skillbill.workflow.goal

import skillbill.workflow.taskruntime.FeatureTaskRuntimeWireArtifactValidator

typealias GoalPlanningPreparationEnvelopeValidator = FeatureTaskRuntimeWireArtifactValidator
