package skillbill.workflow.goal
import skillbill.workflow.taskruntime.model.core.FeatureTaskRuntimeWireArtifactValidator
typealias GoalPlanningPreparationEnvelopeValidator = FeatureTaskRuntimeWireArtifactValidator
