package skillbill.contracts.workflow.featuretask

const val FEATURE_TASK_RUNTIME_CONTRACT_VERSION: String = "0.6"

const val FEATURE_TASK_RUNTIME_REPAIR_RECEIPT_CONTRACT_VERSION: String = "0.3"

const val FEATURE_TASK_RUNTIME_REPAIR_LEDGER_CONTRACT_VERSION: String = "0.1"

const val FEATURE_TASK_RUNTIME_PHASE_OUTPUT_VALIDATION_CONTRACT_VERSION: String = "0.1"

const val FEATURE_TASK_RUNTIME_PHASE_OUTPUT_SCHEMA_ID: String =
  "https://skill-bill.dev/contracts/feature-task-runtime-phase-output-schema.yaml"

const val FEATURE_TASK_RUNTIME_HANDOFF_ENVELOPE_CONTRACT_VERSION: String = "0.1"

const val FEATURE_TASK_RUNTIME_PHASE_LAUNCH_BRIEFING_CONTRACT_VERSION: String = "0.2"

const val FEATURE_TASK_RUNTIME_PHASE_HANDOFF_CONTRACT_VERSION: String = "0.2"

const val FEATURE_TASK_RUNTIME_PERSISTENCE_CONTRACT_VERSION: String = "0.2"

const val FEATURE_TASK_RUNTIME_RUN_INVARIANTS_CONTRACT_VERSION: String = "0.1"

const val FEATURE_TASK_RUNTIME_PROJECTION_MEASUREMENT_CONTRACT_VERSION: String = "0.1"

const val FEATURE_TASK_RUNTIME_REJECTION_MEASUREMENT_CONTRACT_VERSION: String = "0.2"

const val FEATURE_TASK_RUNTIME_DIAGNOSTIC_DEGRADATION_MEASUREMENT_CONTRACT_VERSION: String = "0.1"

const val FEATURE_TASK_RUNTIME_PLANNING_PROJECTIONS_CONTRACT_VERSION: String = "0.3"

const val FEATURE_TASK_RUNTIME_QUARANTINE_CONTRACT_VERSION: String = "0.3"

const val FEATURE_TASK_RUNTIME_IMPLEMENTATION_ATTEMPT_CONTRACT_VERSION: String = "0.2"

const val FEATURE_TASK_RUNTIME_CHECKPOINT_IDENTITY_CONTRACT_VERSION: String = "0.2"

const val FEATURE_TASK_RUNTIME_SHARED_EVIDENCE_PROJECTION_CONTRACT_VERSION: String = "0.2"

const val FEATURE_TASK_RUNTIME_BUILD_RECEIPT_CONTRACT_VERSION: String = "0.1"

const val FEATURE_TASK_RUNTIME_VALIDATION_EVIDENCE_CONTRACT_VERSION: String = "0.1"

const val FEATURE_TASK_RUNTIME_READINESS_EVIDENCE_CONTRACT_VERSION: String = "0.1"
