package skillbill.contracts.telemetry

object LifecycleTelemetryPayloadKeys {
  const val SESSION_ID: String = "session_id"
  const val ERROR: String = "error"
  const val MODE: String = "mode"
  const val TELEMETRY_PAYLOAD: String = "telemetry_payload"
  const val ROUTED_SKILL: String = "routed_skill"
  const val DETECTED_STACK: String = "detected_stack"
  const val FALLBACK: String = "fallback"
  const val FALLBACK_REASON: String = "fallback_reason"
  const val SCOPE_TYPE: String = "scope_type"
  const val INITIAL_FAILURE_COUNT: String = "initial_failure_count"
  const val FINAL_FAILURE_COUNT: String = "final_failure_count"
  const val ITERATIONS: String = "iterations"
  const val RESULT: String = "result"
  const val DURATION_SECONDS: String = "duration_seconds"
  const val DURATION_SECONDS_AVAILABILITY: String = "duration_seconds_availability"
  const val SKILL: String = "skill"
  const val FAILING_CHECK_NAMES: String = "failing_check_names"
  const val UNSUPPORTED_REASON: String = "unsupported_reason"
  const val ACCEPTANCE_CRITERIA_COUNT: String = "acceptance_criteria_count"
  const val ROLLOUT_RELEVANT: String = "rollout_relevant"
  const val FEATURE_FLAG_AUDIT_PERFORMED: String = "feature_flag_audit_performed"
  const val REVIEW_ITERATIONS: String = "review_iterations"
  const val AUDIT_RESULT: String = "audit_result"
  const val COMPLETION_STATUS: String = "completion_status"
  const val HISTORY_RELEVANCE: String = "history_relevance"
  const val HISTORY_HELPFULNESS: String = "history_helpfulness"
  const val SPEC_SUMMARY: String = "spec_summary"
  const val GAPS_FOUND: String = "gaps_found"
  const val COMMIT_COUNT: String = "commit_count"
  const val FILES_CHANGED_COUNT: String = "files_changed_count"
  const val WAS_EDITED_BY_USER: String = "was_edited_by_user"
  const val PR_CREATED: String = "pr_created"
  const val PR_TITLE: String = "pr_title"
  const val REVIEW_FIX_CAP_EXHAUSTED: String = "review_fix_cap_exhausted"
  const val REVIEW_FIX_CAP_EXHAUSTED_AVAILABILITY: String = "review_fix_cap_exhausted_availability"
  const val AUDIT_GAP_ITERATION_COUNT: String = "audit_gap_iteration_count"
  const val AUDIT_FIRST_PASS_CONVERGENCE: String = "audit_first_pass_convergence"
  const val AUDIT_GAP_AVAILABILITY: String = "audit_gap_availability"
  const val AUDIT_GAP_MEASUREMENT_GRAIN: String = "audit_gap_measurement_grain"
  const val AUDIT_REPAIR_ITEM_AVAILABILITY: String = "audit_repair_item_availability"
  const val FINAL_FAILURE_COUNT_AVAILABILITY: String = "final_failure_count_availability"
  const val COMPLETION: String = "completion"
  const val STALE_REASON: String = "stale_reason"
  const val REDACTED_WORKFLOW_ID: String = "redacted_workflow_id"
  const val GOAL_PARENT_WORKFLOW_ID: String = "goal_parent_workflow_id"
  const val GOAL_SUBTASK_ID: String = "goal_subtask_id"
  const val CORRELATION_AVAILABILITY: String = "correlation_availability"
  const val RESOLVED_AGENT_IDS: String = "resolved_agent_ids"
  const val RESOLVED_AGENT_AVAILABILITY: String = "resolved_agent_availability"
  const val LAUNCHED_MODELS: String = "launched_models"
  const val LAUNCHED_MODEL_AVAILABILITY: String = "launched_model_availability"
  const val AGENT_CONTEXT_MEASUREMENT_GRAIN: String = "agent_context_measurement_grain"
}

const val AUDIT_GAP_MEASUREMENT_GRAIN_PER_RUN: String = "audit_gap_rounds_per_run"

const val AGENT_CONTEXT_MEASUREMENT_GRAIN_DISTINCT_PER_RUN: String = "distinct_resolved_agents_per_run"

enum class LifecycleSessionCompletion(val wireValue: String) {
  OPERATOR_COMPLETED("operator_completed"),
  RECONCILER_STALE("reconciler_stale"),
}
