package skillbill.contracts.telemetry

object LifecycleTelemetryPayloadKeys {
  const val SESSION_ID: String = "session_id"
  const val ERROR: String = "error"
  const val MODE: String = "mode"
  const val TELEMETRY_PAYLOAD: String = "telemetry_payload"
  const val ROUTED_SKILL: String = "routed_skill"
  const val DETECTED_STACK: String = "detected_stack"
  const val FALLBACK: String = "fallback"
  const val FALLBACK_REASON: String = "fallback_reason"
  const val SCOPE_TYPE: String = "scope_type"
  const val INITIAL_FAILURE_COUNT: String = "initial_failure_count"
  const val FINAL_FAILURE_COUNT: String = "final_failure_count"
  const val ITERATIONS: String = "iterations"
  const val RESULT: String = "result"
  const val DURATION_SECONDS: String = "duration_seconds"
  const val SKILL: String = "skill"
  const val FAILING_CHECK_NAMES: String = "failing_check_names"
  const val UNSUPPORTED_REASON: String = "unsupported_reason"
  const val ACCEPTANCE_CRITERIA_COUNT: String = "acceptance_criteria_count"
  const val ROLLOUT_RELEVANT: String = "rollout_relevant"
  const val FEATURE_FLAG_AUDIT_PERFORMED: String = "feature_flag_audit_performed"
  const val REVIEW_ITERATIONS: String = "review_iterations"
  const val AUDIT_RESULT: String = "audit_result"
  const val COMPLETION_STATUS: String = "completion_status"
  const val HISTORY_RELEVANCE: String = "history_relevance"
  const val HISTORY_HELPFULNESS: String = "history_helpfulness"
  const val SPEC_SUMMARY: String = "spec_summary"
  const val GAPS_FOUND: String = "gaps_found"
  const val COMMIT_COUNT: String = "commit_count"
  const val FILES_CHANGED_COUNT: String = "files_changed_count"
  const val WAS_EDITED_BY_USER: String = "was_edited_by_user"
  const val PR_CREATED: String = "pr_created"
  const val PR_TITLE: String = "pr_title"
}
