package skillbill.ports.workflow.gitops

import skillbill.ports.workflow.gitops.readiness.ReadinessTreeIdentityGitOperations
import skillbill.ports.workflow.gitops.worktree.WorkflowGitWorktreeOperations

object NoopWorkflowGitOperations :
  WorkflowGitOperations,
  WorkflowGitBranchOperations by NoopWorkflowGitBranchOperations,
  WorkflowGitRemoteOperations by NoopWorkflowGitRemoteOperations,
  WorkflowGitCommitHistoryOperations by NoopWorkflowGitCommitHistoryOperations,
  WorkflowGitWorktreeOperations by NoopWorkflowGitWorktreeOperations,
  SuppressionEvidenceGitOperations by NoopSuppressionEvidenceGitOperations,
  CheckpointHistoryGitOperations by UnavailableCheckpointHistoryGitOperations,
  GoalSubtaskReviewGitOperations by NoopGoalSubtaskReviewGitOperations,
  RepositoryFingerprintGitOperations by NoopRepositoryFingerprintGitOperations,
  ReadinessTreeIdentityGitOperations by UnavailableReadinessTreeIdentityGitOperations,
  RepositoryOwnedPathsGitOperations by UnavailableRepositoryOwnedPathsGitOperations,
  RuntimePhaseFileManifestGitOperations by NoopRuntimePhaseFileManifestGitOperations,
  ScopedStagingGitOperations by UnavailableScopedStagingGitOperations
