package skillbill.contracts.install

object InstallPlanPayloadKeys {
  const val AGENTS: String = "agents"
  const val PLATFORM_PACKS: String = "platform_packs"
  const val SELECTED_PLATFORMS: String = "selected_platforms"
  const val SKILLS: String = "skills"
  const val STAGING_ROOT: String = "staging_root"
  const val STAGING: String = "staging"
  const val TELEMETRY_LEVEL: String = "telemetry_level"
  const val MCP_REGISTRATION: String = "mcp_registration"
  const val RUNTIME_DISTRIBUTION: String = "runtime_distribution"
  const val WINDOWS_SYMLINK_PREFLIGHT: String = "windows_symlink_preflight"
  const val REPLACE_EXISTING_SKILL_BILL_LINKS: String = "replace_existing_skill_bill_links"
  const val AGENT: String = "agent"
  const val PATH: String = "path"
  const val SOURCE: String = "source"
  const val SLUG: String = "slug"
  const val PACK_ROOT: String = "pack_root"
  const val SELECTED: String = "selected"
  const val NAME: String = "name"
  const val KIND: String = "kind"
  const val PLATFORM: String = "platform"
  const val SOURCE_DIR: String = "source_dir"
  const val SKILL_NAME: String = "skill_name"
  const val STAGING_DIR: String = "staging_dir"
  const val CONTENT_HASH: String = "content_hash"
  const val REGISTER: String = "register"
  const val RUNTIME_MCP_BIN: String = "runtime_mcp_bin"
  const val RUNTIME_INSTALL_ROOT: String = "runtime_install_root"
  const val RUNTIME_CLI_BUILD_DIR: String = "runtime_cli_build_dir"
  const val RUNTIME_MCP_BUILD_DIR: String = "runtime_mcp_build_dir"
  const val RUNTIME_CLI_INSTALL_DIR: String = "runtime_cli_install_dir"
  const val RUNTIME_MCP_INSTALL_DIR: String = "runtime_mcp_install_dir"
  const val RUNTIME_LAUNCHER_BIN_DIR: String = "runtime_launcher_bin_dir"
  const val STATE: String = "state"
  const val DECISION: String = "decision"
  const val MESSAGE: String = "message"
  const val PLANNED_STATUS: String = "planned"
}
