package skillbill.infrastructure.launcher.review

object GovernedReviewEvidencePayloadKeys {
  const val ANNOTATIONS: String = "annotations"
  const val READ_ONLY_HINT: String = "readOnlyHint"
  const val DESTRUCTIVE_HINT: String = "destructiveHint"
  const val OPEN_WORLD_HINT: String = "openWorldHint"
  const val ASSIGNMENT_DIGEST: String = "assignment_digest"
  const val SELECTOR: String = "selector"
  const val PATH: String = "path"
  const val LANE: String = "lane"
  const val EXPANSION_ID: String = "expansion_id"
  const val DELIVERY_RECEIPT: String = "delivery_receipt"
  const val RESULTS: String = "results"
  const val CUMULATIVE_BYTES: String = "cumulative_bytes"
  const val EXPANSIONS: String = "expansions"
  const val TERMINAL_OUTCOME: String = "terminal_outcome"
  const val REQUESTS: String = "requests"
  const val REACHABILITY_REASON: String = "reachability_reason"
  const val TOOLS: String = "tools"
  const val REQUESTED_PATH: String = "requested_path"
  const val AUTHORIZED: String = "authorized"
  const val SEQUENCE: String = "sequence"
  const val REFUSED: String = "refused"
  const val REFUSAL_KIND: String = "refusal_kind"
  const val REASON: String = "reason"
  const val BUDGET_KIND: String = "budget_kind"
  const val CONFIGURED_LIMIT: String = "configured_limit"
  const val OBSERVED_VALUE: String = "observed_value"
  const val CONTENT: String = "content"
  const val BYTES: String = "bytes"
  const val EXPANSION_COUNT: String = "expansion_count"
  const val CATEGORY: String = "category"
  const val TARGET: String = "target"
}
