package skillbill.goalrunner

import skillbill.workflow.engine.model.DurableWorkflowArtifacts
import skillbill.workflow.model.goalobservability.GoalObservabilityEvent
import skillbill.workflow.model.goalobservability.GoalObservabilityHistory
import skillbill.workflow.model.goalobservability.goalObservabilityHistoryFromArtifacts
import skillbill.workflow.model.goalobservability.goalObservabilityLatestEventFromArtifacts

internal fun DurableWorkflowArtifacts.goalObservabilityLatestEvent(): GoalObservabilityEvent? =
  goalObservabilityLatestEventFromArtifacts(this)

internal fun DurableWorkflowArtifacts.goalObservabilityHistory(): GoalObservabilityHistory =
  goalObservabilityHistoryFromArtifacts(this)
