package skillbill.goalrunner.subtaskreview

import skillbill.goalrunner.subtaskreview.model.RejectedVerificationFindingsResult as ModelRejectedVerificationFindingsResult

typealias RejectedVerificationFindingsResult = ModelRejectedVerificationFindingsResult
