package skillbill.contracts.codegraph

object CodeGraphMcpKeys {
  const val JSONRPC = "jsonrpc"
  const val ID = "id"
  const val METHOD = "method"
  const val PARAMS = "params"
  const val RESULT = "result"
  const val ERROR = "error"
  const val CODE = "code"
  const val MESSAGE = "message"
  const val PROTOCOL_VERSION = "protocolVersion"
  const val CAPABILITIES = "capabilities"
  const val CLIENT_INFO = "clientInfo"
  const val INSTRUCTIONS = "instructions"
  const val SERVER_INFO = "serverInfo"
  const val NAME = "name"
  const val VERSION = "version"
  const val TOOLS = "tools"
  const val ARGUMENTS = "arguments"
  const val PROJECT_PATH = "projectPath"
  const val CONTENT = "content"
  const val TYPE = "type"
  const val TEXT = "text"
  const val IS_ERROR = "isError"
  const val MCP_SERVERS = "mcpServers"
  const val CODEGRAPH = "codegraph"
  const val URL = "url"
}
