package skillbill.application

import skillbill.workflow.taskruntime.FeatureTaskRuntimeWireArtifactValidator

import skillbill.infrastructure.fs.FeatureTaskRuntimeWireArtifactValidatorAdapter

val realPlanningProjectionValidator: FeatureTaskRuntimeWireArtifactValidator =
  FeatureTaskRuntimeWireArtifactValidatorAdapter()
