package skillbill.application

import skillbill.infrastructure.contracts.FeatureTaskRuntimeWireArtifactValidator as FeatureTaskRuntimeWireArtifactSchemaValidator
import skillbill.ports.taskruntime.FeatureTaskRuntimeWireArtifactValidator as FeatureTaskRuntimeWireArtifactValidatorPort

val realPlanningProjectionValidator: FeatureTaskRuntimeWireArtifactValidatorPort =
  FeatureTaskRuntimeWireArtifactSchemaValidator()
