package skillbill.application

import skillbill.infrastructure.fs.FeatureTaskRuntimePhaseOutputValidatorAdapter
import skillbill.workflow.taskruntime.FeatureTaskRuntimePhaseOutputValidator

val realFeatureTaskRuntimePhaseOutputValidator: FeatureTaskRuntimePhaseOutputValidator =
  FeatureTaskRuntimePhaseOutputValidatorAdapter()
