package skillbill.application

import skillbill.infrastructure.fs.FeatureTaskRuntimeWireArtifactValidator as FeatureTaskRuntimeWireArtifactSchemaValidator
import skillbill.workflow.taskruntime.FeatureTaskRuntimeWireArtifactValidator as FeatureTaskRuntimeWireArtifactValidatorPort

val realPlanningProjectionValidator: FeatureTaskRuntimeWireArtifactValidatorPort =
  FeatureTaskRuntimeWireArtifactSchemaValidator()
