package skillbill.application.review.model
import skillbill.review.context.model.launch.CodeReviewExecutionMode as DomainCodeReviewExecutionMode

typealias CodeReviewExecutionMode = DomainCodeReviewExecutionMode
