package skillbill.contracts.review

object GovernedReviewEvidencePayloadKeys {
  const val ASSIGNMENT_DIGEST: String = "assignment_digest"
  const val NEXT_CURSOR: String = "next_cursor"
  const val ENTRIES: String = "entries"
  const val SELECTOR: String = "selector"
  const val PATH: String = "path"
  const val OWNERS: String = "owners"
  const val LANE: String = "lane"
  const val RUBRIC_ID: String = "rubric_id"
  const val UNIT_ID: String = "unit_id"
  const val EXPANSION_ID: String = "expansion_id"
  const val DELIVERY_RECEIPT: String = "delivery_receipt"
  const val RESULTS: String = "results"
  const val CUMULATIVE_BYTES: String = "cumulative_bytes"
  const val EXPANSIONS: String = "expansions"
  const val TERMINAL_OUTCOME: String = "terminal_outcome"
  const val OPERATION: String = "operation"
  const val CURSOR: String = "cursor"
  const val PAGE_SIZE: String = "page_size"
  const val REQUESTS: String = "requests"
  const val REACHABILITY_REASON: String = "reachability_reason"
  const val NAME: String = "name"
  const val TOOLS: String = "tools"
}
