package skillbill.contracts.review

import skillbill.contracts.SharedPayloadKeys

object ReviewAccountingPayloadKeys {
  const val CONTRACT_VERSION: String = SharedPayloadKeys.CONTRACT_VERSION
  const val KIND: String = "kind"
  const val REVIEW_ID: String = "review_id"
  const val PACKET_DIGEST: String = "packet_digest"
  const val PARENT: String = "parent"
  const val LANES: String = "lanes"
  const val COMMIT_ROUTING_ACCOUNTING: String = "commit_routing_accounting"
  const val PARENT_ANALYSIS_CONSUMPTION: String = "parent_analysis_consumption"
  const val INTEGRATION: String = "integration"
  const val AGGREGATE_COUNTERS: String = "aggregate_counters"
  const val LANE: String = "lane"
  const val ASSIGNMENT_DIGEST: String = "assignment_digest"
  const val LAUNCH_BYTES: String = "launch_bytes"
  const val EVIDENCE_BYTES: String = "evidence_bytes"
  const val RESULT_BYTES: String = "result_bytes"
  const val EXPANSIONS: String = "expansions"
  const val TOOL_CALLS: String = "tool_calls"
  const val MODEL_TURNS: String = "model_turns"
  const val INCLUSIVE_COUNTERS: String = "inclusive_counters"
  const val TERMINAL_OUTCOME: String = "terminal_outcome"
  const val BUNDLE_COMPOSITION_DIGEST: String = "bundle_composition_digest"
  const val SEGMENT_ACCOUNTING: String = "segment_accounting"
  const val UNREVIEWED_SEGMENT_IDS: String = "unreviewed_segment_ids"
  const val EVIDENCE_DELIVERY: String = "evidence_delivery"
  const val SEGMENT_ID: String = "segment_id"
  const val MEASURED_BYTES: String = "measured_bytes"
  const val ENTRY_COUNT: String = "entry_count"
  const val COMPOSITION_DIGEST: String = "composition_digest"
  const val COMMIT_SEQUENCE_DIGEST: String = "commit_sequence_digest"
  const val ROUTING_DIGEST: String = "routing_digest"
  const val COMMIT_COUNT: String = "commit_count"
  const val LANE_COUNT: String = "lane_count"
  const val FOCUSED_COMMIT_COUNT: String = "focused_commit_count"
  const val SKIPPED_COMMIT_COUNT: String = "skipped_commit_count"
  const val FOCUSED_PAIR_COUNT: String = "focused_pair_count"
  const val SKIPPED_PAIR_COUNT: String = "skipped_pair_count"
  const val INCOMPLETE_LANES: String = "incomplete_lanes"
  const val ANALYZED_PAIRS: String = "analyzed_pairs"
  const val ANALYZED_BYTES: String = "analyzed_bytes"
  const val MAX_ANALYSIS_PAIRS: String = "max_analysis_pairs"
  const val MAX_ANALYSIS_BYTES: String = "max_analysis_bytes"
  const val SUMMARIZED_LANE_COUNT: String = "summarized_lane_count"
  const val FINDING_COUNT: String = "finding_count"
  const val COUNTERS: String = "counters"
  const val SKIP_REASON: String = "skip_reason"
  const val REQUIRED_UNITS: String = "required_units"
  const val DELIVERED_UNITS: String = "delivered_units"
  const val REMAINING_UNITS: String = "remaining_units"
  const val REQUEST_COUNT: String = "request_count"
  const val ACCOUNTING_SUMMARY_KIND: String = "accounting_summary"
}
