package skillbill.contracts.review

object SqliteReviewTelemetryPayloadKeys {
  const val LATEST_OUTCOME_COUNTS: String = "latest_outcome_counts"
  const val OUTCOME_TYPE: String = "outcome_type"
  const val ACCEPTED_FINDING_DETAILS: String = "accepted_finding_details"
  const val REJECTED_FINDING_DETAILS: String = "rejected_finding_details"
  const val EVENT_NAME: String = "event_name"
  const val FROM_VERSION: String = "from_version"
  const val TO_VERSION: String = "to_version"
  const val MALFORMED: String = "malformed"
  const val SEVERITY: String = "severity"
  const val AGENT_IDS: String = "agent_ids"
  const val COMMIT_SHAS: String = "commit_shas"
  const val CONFIDENCE: String = "confidence"
  const val DESCRIPTION: String = "description"
  const val LINE: String = "line"
  const val LOCATION: String = "location"
  const val ORIGIN_LAYER_CHAINS: String = "origin_layer_chains"
  const val SPECIALIST_SKILL_NAMES: String = "specialist_skill_names"
  const val UNREVIEWED_SEGMENT_IDS: String = "unreviewed_segment_ids"
  const val LEARNINGS: String = "learnings"
  const val SCOPE_COUNTS: String = "scope_counts"
  const val APPLIED_LEARNING_COUNT: String = "applied_learning_count"
  const val APPLIED_LEARNING_REFERENCES: String = "applied_learning_references"
  const val APPLIED_LEARNINGS: String = "applied_learnings"
  const val REFERENCE: String = "reference"
  const val SCOPE: String = "scope"
  const val TITLE: String = "title"
  const val RULE_TEXT: String = "rule_text"
  const val COMPLETED_PHASE_IDS: String = "completed_phase_ids"
  const val GAPS_FOUND: String = "gaps_found"
  const val FINISHED_AT: String = "finished_at"
  const val PARENT_WORKFLOW_ID: String = "parent_workflow_id"
  const val BLOCKED_REASON: String = "blocked_reason"
  const val ARTIFACT_REF: String = "artifact_ref"
  const val CITATIONS: String = "citations"
  const val CLAIM_VERDICT: String = "claim_verdict"
  const val F_NUMBER: String = "f_number"
  const val FINDING_ID: String = "finding_id"
  const val ISSUE_CATEGORY: String = "issue_category"
  const val PROMPT: String = "prompt"
  const val REPOSITORY_PATH: String = "repository_path"
  const val SEVERITY_ADJUSTMENT: String = "severity_adjustment"
  const val STEP_ID: String = "step_id"
  const val VALUE: String = "value"
  const val WORKFLOW_ID: String = "workflow_id"
}
